apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-docker-image
spec:
  serviceAccountName: build-bot
  taskRef:
    name: kaniko
  inputs:
    resources:
    - name: source
      resourceRef:
        name: github-repository
  outputs:
    resources:
    - name: image
      resourceRef:
        name: dockerhub-repository