apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-github-data-tables
spec:
  workspaces:
    - name: storage
  resources:
    inputs:
      - name: repository
        type: git
    outputs:
      - name: repository
        type: git
  steps:
    - name: install-python-dependencies
      image: python:alpine
      command:
        - pip3
      args:
        - install
        - -r
        - $(resources.inputs.repository.path)/src/python/requirements.txt
        - --user
      env:
        - name: PYTHONUSERBASE
          value: "$(resources.inputs.repository.path)/pipcache"
    - name: generate-github-tables
      image: python:alpine
      workingDir: "$(resources.inputs.repository.path)"
      command: 
        - python
      args:
        - $(resources.inputs.repository.path)/src/python/main.py
      env:
        - name: PYTHONPATH
          value: "$(resources.inputs.repository.path)/pipcache/lib/python3.8/site-packages/"
        - name: GH_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: GH_TOKEN