apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: execute-python-code
spec:
  workspaces:
    - name: build-workspace
      persistentVolumeClaim:
        claimName: workspace
      subPath: pipcache
  taskRef:
    name: execute-python-code
  inputs:
    resources:
    - name: repository
      resourceRef:
        name: github-repository