namespace: tekton-builds

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

secretGenerator:
  - name: github-token
    env: secrets/github-token.env
  - name: dockerhub-auth-credentials
    type: kubernetes.io/basic-auth
    env: secrets/dockerhub.env

resources:
  - namespace.yml
  - tektonServiceAccount.yml
  - tektonClusterRoleBinding.yml
  - kaniko.yml
  - githubRepositoryPipelineResource.yml
  - dockerHubRepositoryPipelineResource.yml
  - sharedDataPersistentVolumeClaim.yml
  - buildGithubDataTablesTask.yml
  - pipeline.yml
  - pipelineRun.yml

  # - buildHTMLTask.yml
  # - buildPDFFullTask.yml
  # - buildPDFCondensedTask.yml
