language: python
python:
  - "3.7.1"
services:
  - docker

cache:
  directories:
    - $TRAVIS_BUILD_DIR/output/

before_script:
  - sudo apt-get install -y ghostscript

jobs:
  include:
    - stage: Build HTML and PDF
      script:
        - make execute_python
        - make build_html
        - make build_pdf_full
        - make build_pdf_condensed
        - make optimize_pdf

    - stage: Build Docker Image and Push to Docker Hub
      if: tag is present
      script:
        - make build_docker_image 
        - make push_docker_image 

    - stage: Deploy to Github Pages
      script:
        - if [ ! -z "$CUSTOM_DOMAIN" ]; then echo $CUSTOM_DOMAIN > $TRAVIS_BUILD_DIR/output/CNAME; fi
      if: tag is present
      deploy:
        provider: pages
        target_branch: master
        skip_cleanup: true
        local_dir: $TRAVIS_BUILD_DIR/output/
        token: $GH_TOKEN
        on:
          tags: true
