sudo: required

services:
  - docker

before_install:
  - mkdir -p output/{en,ptbr}

script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/documents/ -e 'ASCIIDOCTOR_THEME=riak' -e 'ASCIIDOCTOR_PLUGIN=google-analytics-docinfoprocessor,tel-inline-macro' integr8/alpine-asciidoctor-helper html resume-en.adoc resume-ptbr.adoc
  - docker run --rm -v $TRAVIS_BUILD_DIR:/documents/ -e 'ASCIIDOCTOR_PLUGIN=google-analytics-docinfoprocessor,tel-inline-macro' integr8/alpine-asciidoctor-helper pdf resume-en.adoc resume-ptbr.adoc
  - cp output/resume-en.html output/index.html
  - mv output/resume-en.html output/en/index.html
  - mv output/resume-en.pdf output/en/resume.pdf
  - mv output/resume-ptbr.html output/ptbr/index.html
  - mv output/resume-ptbr.pdf output/ptbr/resume.pdf
  - if [ ! -z "$CUSTOM_DOMAIN" ]; then echo $CUSTOM_DOMAIN > output/CNAME; fi

deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  local_dir: output/
  github_token: $GH_TOKEN
  on:
    branch: development