sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output resume.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output resume.adoc
  - mv output/resume.html output/index.html
  - echo 'fabioluciano.me' > output/CNAME

deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  local_dir: output/
  github_token: $GH_TOKEN
  on:
    branch: development