language: python
python:
  - "3.7.1"
services:
  - docker

cache:
  directories:
    - $TRAVIS_BUILD_DIR/output/

jobs:
  include:
    - stage: Build HTML and PDF
      if: tag is present
      script:
        - make execute_python
        - make build_html
        - make build_pdf
        - if [ ! -z "$CUSTOM_DOMAIN" ]; then echo $CUSTOM_DOMAIN > $TRAVIS_BUILD_DIR/output/CNAME; fi
        - ls -lah
      deploy:
        provider: pages
        target_branch: gh-pages
        cleanup: false
        local_dir: $TRAVIS_BUILD_DIR/output/
        token: $GH_TOKEN
        on:
          tags: true

    - stage: Build Docker Image and Push to Docker Hub
      if: tag is present
      script:
        - make build_docker_image 
        - make push_docker_image 