language: python
python:
  - "3.7.1"
services:
  - docker

cache:
  directories:
    - $TRAVIS_BUILD_DIR/output/

jobs:
  include:
    - stage: Build HTML
      if: tag is present
      script:
        - make build_html

    - stage: Build PDF
      if: tag is present
      script:
        - make build_pdf

    - stage: Build Docker Image
      if: tag is present
      script:
        - make build_docker_image 

    - stage: Deploy domain configuration file
      if: tag is present
      script: 
        - if [ ! -z "$CUSTOM_DOMAIN" ]; then echo $CUSTOM_DOMAIN > output/CNAME; fi

    - stage: Deploy to Github pages
      deploy:
        provider: pages
        target_branch: gh-pages
        cleanup: false
        local_dir: $TRAVIS_BUILD_DIR/output/
        token: $GH_TOKEN
        on:
          tags: true