[[education]]

ifdef::backend-html5[]
== icon:graduation-cap[] Educação
endif::[]

ifdef::backend-pdf[]
== Educação
endif::[]

=== Acadêmico 

==== Pontifícia Universidade Católica de Minas Gerais - Arquitetura de Software Distribuído
icon:calendar[title="Período"] `2019 até o momento` - *Diploma de Pós-Graduação Lato Sensu*
Arquiteto de Software de Sistemas Distribuídos

==== Centro Universitário IESB - Análise e Desenvolvimento de Sistemas
icon:calendar[title="Período"] `2012 - 2014` - *Diploma de Bacharelado*
Analista e Desenvolvedor de Sistemas

==== Centro Universitário IESB - Curso de Extensão em Análise e Projeto de Sistemas
icon:calendar[title="Período"] `2012 - 2012` - *Curso de Extensão*
Analista e Projetista de Sistemas

==== Centro Universitário IESB - Curso de Extensão em Suporte de Tecnologia da Informação
icon:calendar[title="Período"] `2013 - 2013` - *Curso de Extensão*
Analista de Tecnologia da Informação

==== Centro Universitário IESB - Ciência da Computação
icon:calendar[title="Período"] `2007 - Não Concluído`
Cientista da Computação

=== Idiomas

Português:: Língua nativa
Inglês:: Leitura(fluente), escrita(intermediário) e conversação(intermediário)
Espanhol:: Leitura(fluente), escrita(intermediário) e conversação(intermediário)
Francês:: Leitura(básico), escrita(básico) e conversação(básico)

=== Eventos e Palestras

==== Containers para pessoas ansiosas - DF
icon:user[title="Papel"] Palestrante icon:calendar[title="Período"] `01/2020` icon:map-marker[] Brasília / DF

==== Containers para pessoas ansiosas - PB
icon:user[title="Papel"] Palestrante icon:calendar[title="Período"] `11/2019` icon:map-marker[] Campina Grande / PB