[[professional-experience]]

ifdef::backend-html5[]
== icon:suitcase[] Experiências profissionais
endif::[]

ifdef::backend-pdf[]
== Experiências profissionais
endif::[]

--
**Arquiteto de Soluções** +
icon:calendar[title="Período"] Janeiro de 2018 até o Presente +
icon:building[title="Empregador"] {link-sonda}[SONDA IT, role="external", window="_blank"] +
icon:chevron-circle-right[title="Cliente"] Fábrica de Software

ifeval::[{with_activities} == true]
ifdef::backend-html5[]
.Atividades executadas
[%collapsible]
====
endif::[]
- Criação de infraestrutura como código utilizando o Terraform e CloudFormation para implantação de soluções utilizadas por todos os clientes da Fábrica de Software;
- Implantação e configuração de ferramentas de integração e entrega contínua em ambiente empresarial (Jenkins, SonarQube, Sonatype Nexus, Gitlab, etc.);
- Análise, implantação e configuração de elementos para implantação de balanceamento de carga e escalabilidade em ferramentas de integração/entregra contínua e aplicações utilizando proxy reverso (HAProxy) e programaticamente, utilizando suas APIs.
- Implementação e implantação da automatização de configurações e propriedades em ferramentas utilizando Apache Groovy;
- Implantação do conceito de núvem privada para orquestração de recursos sob demanda;
- Implantação de nuvens privadas e aplicações utilizando infraestrutura como código (IaC), com Ansible, Fabric e Docker Compose;
- Composição de ambientes de integração/entrega contínua em ambientes distribuídos geograficamente;
- Definição de processos de integração/entrega contínua de aplicações, bem como definições de requisitos mínimos de segurança e qualidade em aplicações;
- Orquestração do processo de integração/entrega contínua utilizando ferramentas (Jenkins, SonarQube, Sonatype Nexus, Gitlab, etc.);
- Implantação da automatização de testes unitários(JUnit,PHPUnit, Karma, Jasmine), funcionais(Cucumber, Codeception, Behat, Cucumberjs) e de carga(JMeter) em aplicações empresariais;
- Projeto e implantação de soluções baseadas em núvem utilizando os provedores Amazon Web Services e Microsoft Azure;
ifdef::backend-html5[]
====
endif::[]
endif::[]
Tecnologias:: Cloud Computing, AWS, Azure, Terraform, Ansible, Docker, Java, PHP, CAS, Microserviços, DevOPS, Jenkins, Angular, Jenkins, GitLab, Nexus, SonarQube, Pipeline, Integração Contínua, Entrega Contínua, Qualidade Contínua e LogStash.
--

'''

--
**Arquiteto de Software** +
icon:calendar[title="Período"] Julho de 2016 até Dezembro de 2017 +
icon:building[title="Empregador"] {link-ctis}[CTIS Tecnologia, role="external", window="_blank"] +
icon:chevron-circle-right[title="Cliente"] {link-ministry-mctic}[Ministério da Ciência e Tecnologia]

ifeval::[{with_activities} == true]
ifdef::backend-html5[]
.Atividades executadas
[%collapsible]
====
endif::[]
- Desenvolvimento e manutenção de uma arquitetura arquitetura com microserviços;
- Implantação das ferramentas para orientar a implantação da filosofia DevOps no órgão;
- Análise dos logs dos microserviços, bem como a criação de gatilhos da stack de automação utilizando o LogStash;
- Monitoramento dos microserviços utilizando o Prometheus;
- Criação de pipelines de integração/entrega/qualidade contínua em projetos Java(JEE), Angular.js e PHP;
- Criação de containers Docker para orquestração dos microserviços;
- Implantação do balanceamento de carga e alta disponibilidade com o HaProxy;
- Implementação da implantação automatizada dos microserviços utilizando o Ansible;
ifdef::backend-html5[]
====
endif::[]
endif::[]

Tecnologias:: Java, PHP, CAS, Microserviços, DevOPS, Jenkins, Angular, Jenkins, GitLab, Nexus, SonarQube, Pipeline, Integração Contínua, Entrega Contínua, Qualidade Contínua e LogStash.
--

'''

--
**Arquiteto de Software** +
icon:calendar[title="Período"] Abril de 2016 a Julho de 2016 +
icon:building[title="Empregador"] {link-ctis}[CTIS Tecnologia, role="external", window="_blank"] +
icon:chevron-circle-right[title="Cliente"] {link-ministry-mdic}[Ministério do Desenvolvimento Indústria e Comércio]

ifeval::[{with_activities} == true]
ifdef::backend-html5[]
.Atividades executadas
[%collapsible]
====
endif::[]
- Desenvolvimento e manutenção de uma arquitetura orientada a serviços (SOA);
- Implementação arquitetural de sistemas utilizando Phalcon PHP, Symfony e Laravel;
- Implementação de componentes DAO para habilitação de reutilização em todas as arquiteturas;
- Desenvolvimento e implantação de uma arquitetura AngularJS;
- Documentação arquitetural de sistemas construídos;
- Documentação de implantação das aplicações;
- Manutenção e criação de Jobs no Jenkins;
- Estabelecimento de diretrizes de seguranças a serem seguidas pelos softwares desenvolvidos;
- Definição de políticas de qualidade a serem avaliadas pela análise estática;
- Monitoramento e manutenção de padrões de qualidade de software com o SonarQube;
- Gerenciamento de versões e candidatas usando o Sonatype Nexus;
- Criação de provas de conceitos de containerização de aplicações.
ifdef::backend-html5[]
====
endif::[]
endif::[]

Tecnologias:: SOA, PHP, Phalcon, Symfony, Laravel, DAO, Arquitetura, AngularJS, Jenkins, SonarQube, Sonatype Nexus, Docker, Container.
--

'''

--
**Arquiteto de Software** +
icon:calendar[title="Período"] Março de 2015 a Dezembro 2015 +
icon:building[title="Empregador"] {link-ctis}[CTIS Tecnologia, role="external", window="_blank"] +
icon:chevron-circle-right[title="Cliente"] {link-ministry-integration}[Ministério da Integração Nacional]

ifeval::[{with_activities} == true]
ifdef::backend-html5[]
.Atividades executadas
[%collapsible]
====
endif::[]
- Desenvolvimento e manutenção de arquiteturas orientadas a serviços (SOA);
- Desenvolvimento de duas arquiteturas paa o Backend. Uma usando o Laravel para a construção de aplicações com PHP, e outra, em JAVA, utilizando o framework Spring;
- Desenvolvimento de uma arquitetura frontend utilizando AngularJS;
- Criação de uma ferramenta de scaffold de componentes AngularJs;
- Documentação arquitetural de sistemas construídos;
- Manutenção e criação de Jobs no Jenkins;
ifdef::backend-html5[]
====
endif::[]
endif::[]

Tecnologias:: SOA, PHP, Java, Laravel, Spring, AngularJS, Jenkins.
--

'''

--
**Desenvolvedor PHP** +
icon:calendar[title="Período"] Fevereiro de 2014 a Março de 2015 +
icon:building[title="Empregador"] {link-ctis}[CTIS Tecnologia, role="external", window="_blank"] +
icon:chevron-circle-right[title="Cliente"] {link-ministry-integration}[Ministério da Integração Nacional]

ifeval::[{with_activities} == true]
ifdef::backend-html5[]
.Atividades executadas
[%collapsible]
====
endif::[]
- Desenvolvimento e manutenção do backend de softwares em PHP, utilizando Zend, Symfony e Laravel como framework;
- Desenvolvimento e manutenação do frontend utilizando  HTML, Javascript (JQuery) e CSS.
ifdef::backend-html5[]
====
endif::[]
endif::[]

Tecnologias:: PHP, Zend Framework, Symfony, Laravel, HTML, Javascript, JQuery e CSS.
--

'''

--
**Analista de configuração de mudança** +
icon:calendar[title="Período"] Abril de  2011 a Julho de  2012 +
icon:building[title="Empregador"] {link-gestao-ti}[Gestão TI, role="external", window="_blank"] +

ifeval::[{with_activities} == true]
ifdef::backend-html5[]
.Atividades executadas
[%collapsible]
====
endif::[]
- Manutenção e gerenciamento de servidores de aplicação;
- Gerenciamento de linhas de base, branches e tags dos artefatos;
- Entrega dos artefatos gerados;
- Criação de políticas de seguranças das aplicações;
ifdef::backend-html5[]
====
endif::[]
endif::[]

Tecnologias:: Linux, Servidores, Windows, Linux, Subversion.
--

// === PHP Developer at Gestão TI

// icon:calendar[title="Período"] `March 2012 to April 2012` +
// icon:building[title="Empregador"] {link-gestao-ti}[Gestão TI, role="external", window="_blank"] +

// ifdef::backend-html5[]
// .Atividades executadas
// [%collapsible]
// ====
// endif::[]
// - Development and maintenance of softwares developed using PHP and SQL Server; 
// - Development of frontend using HTML, Javascript (JQuery) and CSS; 
// - Migration from legacy ASP softwares to PHP.
// ifdef::backend-html5[]
// ====
// endif::[]

// Tecnologias:: ...

// === System Administrator at Fábrica de Ideias

// icon:calendar[title="Período"] `January 2011 to June 2011` +
// icon:building[title="Empregador"] {link-fabrica-ideias}[Fábrica de Ideias, role="external", window="_blank"] +

// ifdef::backend-html5[]
// .Atividades executadas
// [%collapsible]
// ====
// endif::[]
// - Administration of 20 company servers;
// - Maintenance of application servers using the Apache HTTPd for backend, and Lighttpd for frontend;
// - Maintenance of server databases in clustered environment, ensuring high service availability;
// - Maintenance of reverse proxy server using Squid ;
// - SVN server administration;
// - Monitoring servers and services using Zabbix.
// ifdef::backend-html5[]
// ====
// endif::[]

// Tecnologias:: ...

// === PHP Developer at Fábrica de Ideias

// icon:calendar[title="Período"] `August 2008 to December 2010` +
// icon:building[title="Empregador"] {link-fabrica-ideias}[Fábrica de Ideias, role="external", window="_blank"] +

// ifdef::backend-html5[]
// .Atividades executadas
// [%collapsible]
// ====
// endif::[]
// - Development and maintenance of solutions developed using PHP and MySQL;
// - Development of frontend using HTML, Javascript (JQuery) and CSS;
// - Creation of an tool for marking areas in images to OCR. The markings are made using Python and wxWidgets, to ensure interoperability of the application;
// - Creation of an handmade Load Balance to garantee the high avaliability of services in operation;
// - Use of subversion for versioning releases of the software developed.
// ifdef::backend-html5[]
// ====
// endif::[]

// Tecnologias:: PHP, MySQL, Javascript, HTML, CSS, Subversion, ShellScript 